2 caricament file
R-and-LaTeX/CorsoDiR pull request #12
Opened 2017-10-13 14:10 UTC by mzanella

**Reference to the issue (_mandatory_)**: closes #2 

**Description**
caricamento dei file con cherry picking anche

**Memo**: quando hai mergiato la PR chiudi la issue associata :blush:

2017-10-13 15:24 UTC, Polpetta commented
Ho compilato il tuo pdf ma mi viene vuoto senza contenuto. C'è qualcosa che non va!

2017-10-13 15:36 UTC, Polpetta requested changes
Rivedi un poco di correzioni che ti ho fatto. Poi c'è un casino con i file: come mai c'è il `.tex` generato caricato nel repo? :thinking:

2017-10-13 15:36 UTC, Polpetta commented on .gitignore
> +.Rhistory
Non lo prende dentro `/res/` :confused:

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +noi ne vedremo una per ciascuno di questi. R mette a disposizione il comando
`di essi`

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +\texttt{read.table} che è un comando generico per laggere dati da file.
È una funzione? Perchè se si metterei le parentesi. Poi non so vedi te, l'importante è che ci mettiamo d'accordo così abbiamo una cosa uniforme

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +\subsection{Caricamento da txt}
O `.txt` o `da testo`, non una via di mezzo :sweat_smile:

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +  \item il nome del file(se il file è nella stessa cartella da cui lanciamo R)
Manca lo spazio prima della parentesi

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +riportate le principale. Per una lista esaustiva è sufficiente dare il comando
`principali`

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +\texttt{?read.delim}.
Anche qui è una funzione?

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +\subsection{Caricamento da xls}
Anche qui, o `.xls` o `Excel 2003` o quel che è

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +Anche in questo caso è possibile specificare altre opzione che però noi non
`opzioni`

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +vedremo. È inoltre possibile specificare alcune delle opzioni disponibili per
`opzioni` viene ripetuto in 3 righe. Se trovi un sinonimo diventa più leggibile il tutto! :blush:

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +\subsection{Caricamento da xlsx}
Anche qui, o `.xlsx` o `Excel 2017` o come si chiama il nuovo formato

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.Rnw
> +il file, con l'estensione \texttt{.RData} (è possibile anche specificare il
Le altre volte non avevi messo il punto prima di dire `con l'estensione`

2017-10-13 15:36 UTC, Polpetta commented on res/Rnw/10-CaricamentoFile.tex
> +\section{Caricamento dati da file}
Ehm perchè c'è il compilato dell' `.Rnw`? :thinking:

2017-10-14 08:17 UTC, Polpetta commented
Inoltre perchè il tuo sezionamento parte da 0?
![image](https://user-images.githubusercontent.com/5928183/31574115-d4de12fa-b0c8-11e7-8698-0ae4ce89042a.png)
Non è che ti sei dimenticato di mettere `chapter` tipo?

2017-10-14 08:49 UTC, mzanella commented on .gitignore
> +.Rhistory
Quindi che faccio?:sweat_smile: tolgo solo i file generati?

2017-10-14 09:02 UTC, mzanella commented on res/Rnw/10-CaricamentoFile.Rnw
> +\texttt{?read.delim}.
No qui è la chiamata all'help

2017-10-14 09:12 UTC, Polpetta commented on .gitignore
> +.Rhistory
No prova a vedere se tipo mettendo `./**/.Rhistory` funge!

2017-10-14 09:30 UTC, mzanella commented on .gitignore
> +.Rhistory
A me non lo vede il `.Rhistory`:sweat_smile:

2017-10-14 09:59 UTC, Polpetta commented on .gitignore
> +.Rhistory
Boh! 😁  Allora lascia così com'è

2017-10-14 10:00 UTC, Polpetta commented
Ma il file `.tex` lo teniamo? Non ho capito a cosa serve se c'è il `.Rnw`

2017-10-16 07:55 UTC, Polpetta approved these changes

2017-10-16 08:05 UTC, merged